spring:
  config:
    import: optional:file:.env
  kafka:
    #localhost:9092 on local machine
    bootstrap-servers: kafka:9092
    producer:
      properties:
        spring.json.add.type.headers: false
        spring.json.trusted.packages: "*"
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  application:
    name: crypto-transaction-monitoring
  datasource:
    url: jdbc:postgresql://localhost:5432/crypto_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
crypto:
  url : ${CRYPTO_URL}
  token : ${CRYPTO_TOKEN}