spring:
  application:
    name: crypto-transaction-monitoring
  datasource:
    url: jdbc:postgresql://localhost:5432/crypto_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  api:
    crypto-external-api:
      base-url: ${CRYPTO_EXTERNAL_API_BASE_URL}
      token: ${CRYPTO_EXTERNAL_API_TOKEN}
